### ISSUE TITLE
[1.2] Gluten 1.2.0 Issue Tracker

### ISSUE THREAD

**Issue by weiting-chen** [apache/incubator-gluten#7126]
### Backend

VL (Velox)

### Bug description

This is a tracker to collect all the critical issues in Gluten v1.2.0 and plan to be fix in v1.2.1.
Discussion in here: https://github.com/apache/incubator-gluten/discussions/7125

#### Shuffle, Spill related bug fix

- [x] Spill Hang fix has been done in https://github.com/apache/incubator-gluten/pull/7943
- [x] #6422 has been done in #7991
- [x] #7861 is working in #8078 

#### Celeborn related bug fix

- [x] #6432 has been done in #7922 
- [x] #6657 has been done in #7922 

#### Uniffle related bug fix

- [x] #6698 has been done in #7994
- [x] #7525 has been done in #7994
- [x] #7560 has been done in #7994

#### Compile & Package related bug fix

- [x] #6560 has been done in #7974 
- [x] #6569 has been done in #7974 
- [x] #6730 has been done in #7974 
- [x] #7117 has been done in #7974 

#### CI/CD bug fix

- [x] #6911 has been done in #6945 
- [x] #6919 has been done in #6945
- [x] Upgrade GHA artifacts version has been done in #7293 
- [x] Port CI changes has been done in #7314 
- [x] skip data gen in OOM test has been done in #7329 
- [x] CK Backend CI/CD refresh has been done in #7936 
- [x] #8027 has been done in #8075
- [x]  #8034 has been done in #8075
- [x] #8042 has been done in #8075
- [x] #8047 has been done in #8059

#### Other bug fix

- [x] #6563 has been done in #7919 
- [x] #6573 has been done in #7973 
- [x] #6679 has been done in #7919 
- [x] #6901 has been done in #6941 
- [x] #7025 has been done in #7973
- [x] #7038 has been done in #7699 
- [x] #7121 has been done in #7988 
- [x] #7132 has been done in #7973 
- [x] #7448 has been done in #7988 
- [x] BNLJ not fallback issue has been done in #7569 
- [x] devtoolset-9 for centos7 has been done in #7678 

### OAP Velox branch-1.2

- [x] https://github.com/facebookincubator/velox/pull/9868 has been done in https://github.com/oap-project/velox/pull/503
- [x] https://github.com/facebookincubator/velox/pull/10583 has been done in https://github.com/oap-project/velox/pull/505
- [x] https://github.com/facebookincubator/velox/pull/10755 has been done in https://github.com/oap-project/velox/pull/505
- [x] https://github.com/facebookincubator/velox/pull/11298 has been done in https://github.com/oap-project/velox/pull/505

**Comment by zhouyuan** [comment]
Note
1.2.1 is planned for Nov/30

**Comment by weiting-chen** [comment]
1.2.1 code freeze is planned on Nov. 25
