### ISSUE TITLE
[VL] umbrella performance issues during Gluten adoption

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#7269]
### Description

- [ ] task killed by yarn, #6947 
- [ ] global memory OOM, #7249
- [ ] bad spill performance #7159
- [ ] bad R2C performance #7223
- [ ] bad BHJ performance when broadcast table is large
- [ ] UDF
- [ ] object hashagg

**Comment by FelixYBW** [comment]
@z123

**Comment by boneanxs** [comment]
@FelixYBW Hi, what does "object hashagg" mean, could you please elaborate more? Thanks!

**Comment by FelixYBW** [comment]
> [@FelixYBW](https://github.com/FelixYBW) Hi, what does "object hashagg" mean, could you please elaborate more? Thanks!

It's a type of hashagg in spark. A Spark operator which isn't supported in Gluten/Velox yet.
