### ISSUE TITLE
[VL] Gluten 2025 roadmap

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#8226]
### Description

2024 is almost gone. Time to define 2025 features. Here is some from my mind. Feel free to add more or comment

- [ ] Spark 4.0 support
- [ ] Stage level resource management(#4392 )
- [ ] Spill enhancement and performance #3030
- [ ] Hash table broadcast support in BHJ
- [ ] Dictionary support in shuffle
- [ ] Pyspark Support including Python UDF/Arrow UDF
- [ ] Other Accelerator such as GPU, FPGA Support
- [ ] Stability improvement, result mismatch issues #4652
- [ ] Coverage improvement, operators, functions
- [ ] Full datalake support
- [ ] Performance improvement: spill, sort and others

**Comment by zhanglistar** [comment]
What about supporting Flink framework?

**Comment by Myracle** [comment]
Any pan or discussion about flink?

**Comment by zhztheplayer** [comment]
@zhanglistar @Myracle 

It waits for discussion.

Does someone want to open / host a discussion for the topic? cc @apache/gluten-committers

**Comment by jinchengchenghh** [comment]
Do we need to do complex data type support and optimization such as row to column optimization for complex data type?

**Comment by FelixYBW** [comment]
> Do we need to do complex data type support and optimization such as row to column optimization for complex data type?

Yes, currently R2C with complex type is too expensive

**Comment by MacChen01** [comment]
What about support openEuler OS ?

**Comment by FelixYBW** [comment]
> What about support openEuler OS ?

Can vcpkg=on work on openEuler?

**Comment by felipepessoto** [comment]
@FelixYBW what you mean by `Full Datalake support`? Is it to improve support and performance for Delta tables?

**Comment by FelixYBW** [comment]
> @FelixYBW what you mean by `Full Datalake support`? Is it to improve support and performance for Delta tables?

some features are not supported yet in Velox and Gluten.

**Comment by VaibhavFRI** [comment]
@FelixYBW what will be included in **ARM architecture support**? Will Gluten, Velox utilize SVE in ARM to improve performance?

**Comment by FelixYBW** [comment]
> @FelixYBW what will be included in **ARM architecture support**? Will Gluten, Velox utilize SVE in ARM to improve performance?

It means we will setup CI or jenkins to verify on the ARM platform. SVE is part of the performance optimization work.

**Comment by surnaik** [comment]
@FelixYBW Happy new year and thanks for sharing the roadmap, will we add MOR table support for Hudi as part of full data lake support?

**Comment by zhouyuan** [comment]
> @FelixYBW Happy new year and thanks for sharing the roadmap, will we add MOR table support for Hudi as part of full data lake support?

@surnaik Hi, yes there's a draft on this already, it's pending on Velox side change
https://github.com/apache/incubator-gluten/pull/8056

**Comment by FelixYBW** [comment]
> @surnaik Hi, yes there's a draft on this already, it's pending on Velox side change #8056

@zhouyuan do we have a list of missing support for delta lake like this?

**Comment by liujiayi771** [comment]
@zhouyuan @surnaik This PR does not support Hudi, it supports Iceberg's equality MOR table. We have already supported Iceberg's position MOR table. For Hudi, supporting MOR currently seems quite difficult. The native engine only has good support for deletion vector type MOR tables.

**Comment by vinothchandar** [comment]
cc @xushiyan @yihua.

**Comment by jinchengchenghh** [comment]
We can also support query trace.

**Comment by kevinw66** [comment]
@FelixYBW @MacChen01 I'd to do some compatibility work related to the openEuler, I was wondering if the PRs will be accepted?

**Comment by waywtdcc** [comment]
Do we have WeChat or DingTalk groups？

**Comment by PHILO-HE** [comment]
> Do we have WeChat or DingTalk groups？

@waywtdcc, see https://github.com/apache/incubator-gluten?tab=readme-ov-file#6-community

**Comment by pjy324** [comment]
Any plans or discussions for Gluten-Trino project integration?

**Comment by FelixYBW** [comment]
> Any plans or discussions for Gluten-Trino project integration?

Would you like to contribute to it? The topic is raised several times but no contributor committed on it.

**Comment by MrFireChow** [comment]
Is [Gluten 2026 Roadmap] prepared?

**Comment by weiting-chen** [comment]
> Is [Gluten 2026 Roadmap] prepared?

We have created Gluten 2026 Roadmap, please move to the new page for better understanding.
