### ISSUE TITLE
[VL] OAP velox commits track

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#8287]
### Description

Current velox commits in oap/velox:

- [ ] [[5962 ] Support struct column reading with different schemas (5962)]
- [ ] [[6020 ] Spark sql avg agg function support decimal]
- [ ] [[oap1] Register merge extract companion agg functions without suffix]
- [ ] [[oap2] Treat timestamp partition value as UTC]
- [ ] [[oap3] Delete website folder due to security issues
- [ ] [[oap4] Set writeInt96AsTimestamp to true, will remove after int64 sup…]
- [ ] [[oap5] Support scan filter for decimal in ORC]
- [ ] [[oap6] fix unit tests]
- [ ] [[11691] feat: Add get_json_object Spark function]
- [ ] [[oap7] adding simdjson/gflags changes]

3 has PRs in upstream velox
7 no PR submitted yet
