### ISSUE TITLE
[CORE][umbrella] Configuration enhancements

### ISSUE THREAD

**Issue by yikf** [apache/incubator-gluten#8326]
### Description

As discussed in https://github.com/apache/incubator-gluten/issues/6970, we plan to enhance the gluten configuration, and the specific enhancement solutions can be found in section https://github.com/apache/incubator-gluten/issues/6970#issuecomment-2511452471.

This issue serves as an umbrella to record the task list that we need to include to achieve our goals, because enhance config involves a large number of files, splitting multiple tasks facilitates code review and reduces the risk of introducing other problems.

- [ ] Introduce the ConfigEntry to make the config definition more flexible.
- [ ] Split the configuration into individual modules that belong to each other.
- [ ] Split configuration into two separate files: one static and one non-static.
- [ ] Standardize configuration naming, log the deprecated config name if used.
- [ ] Support generate gluten configuration doc and check it. https://github.com/apache/incubator-gluten/issues/8070

**Comment by baibaichen** [comment]
@yikf as discussed in the offline, there are 2  requirement

1. Pass spark config to backend. For example, ch backend need `spark.sql.caseSensitive` to choose compare behavior.
2. Pass value type to backend. currently we use `ConfigMap` which use assum value is string type.

**Comment by FelixYBW** [comment]
@yikf Is the enhancement finished? Is there a readme about how to add a configuration?

**Comment by yikf** [comment]
> [@yikf](https://github.com/yikf) Is the enhancement finished? Is there a readme about how to add a configuration?

It's not completed yet. I will keep following up in the next few days. 

Eventually, there will be a configuration.md file to describe the configuration. Regarding the description of how to add the configuration, I can add it in this file.
